const $=s=>document.querySelector(s);
$("#menu").onclick=()=>{$("#nav").classList.toggle("open")};
document.querySelectorAll("#nav a").forEach(a=>a.onclick=()=>{$("#nav").classList.remove("open")});
const topBtn=$("#top"); const progress=$("#progress");
window.addEventListener("scroll",()=>{let max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max?scrollY/max*100:0)+"%";topBtn.classList.toggle("show",scrollY>500)}, {passive:true});
topBtn.onclick=()=>scrollTo({top:0,behavior:"smooth"});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.12});
document.querySelectorAll(".reveal").forEach(x=>io.observe(x));
const theme=$("#theme"); if(localStorage.getItem("bbk-theme")==="dark")document.body.classList.add("dark");
theme.onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("bbk-theme",document.body.classList.contains("dark")?"dark":"light")};
$("#year").textContent=new Date().getFullYear();